name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: elm make src/Main.elm --output=public/main.js --optimize
      - name: Deploy to S3
        run: aws s3 sync ./public/ s3://hwaet.autophagy.io --delete
